services:
  - type: web
    name: Mechanical-Assignment
    runtime: python
    buildCommand: pip install -r requirements.txt && python -m flask db upgrade
    startCommand: gunicorn app:app 
    envVars:
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mech_pro
          property: connectionString
